### ISSUE TITLE
Client crash 

### ISSUE THREAD

**Issue by kojul** [TSSN/Sinful-Skies#22]
Not exactly a huge issue, but client crashed after I had died. I had gotten knocked off the platform by an Ent as I died in a hardcore world. No idea here.

http://paste.atlauncher.com/view/71c8190a

**Comment by artdude543** [comment]
Yeah we have seen this bug before, it's a odd crash but its basically the AI of the mobs trying to break a block bug seems to bug out when its a Crafting Station. I will report this to the mod developers also to see if something could be done to catch the error instead of crashing. But I've only seen this issue a few times so its a rare crash but I will still look into it :)

**Comment by artdude543** [comment]
Yeah so after testing this is only seems to happy under certain conditions but does not cause world corruptions. Just means having to start the game again, but I've reported the issue to the mod creators and they may add additional checker their side.
