### ISSUE TITLE
Enviromine bug??

### ISSUE THREAD

**Issue by PixelPrincess80** [TSSN/Sinful-Skies#9]
Not sure if it was designed this way or not but the torches seem to heat you up when you are near them but lava does not.  Seems you could use lava in such a way to light up your base if you place it carefully and not have it heat you up making the game a bit easier... especially once your base is made out of a non flamable material.

**Comment by MindlessPuppetz** [comment]
Lava should be working to heat you up in v.1.4a it has been working on our dev server/clients just fine. There is however a bug in 1.4 with enviromine where the client desyncs and the temp and thirst freeze altogether. This I believe was fixed in the latest enviromine release and will be working properly in 1.5a
